# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y docker.io git
     git clone https://github.com/vyos/vyos-build.git /home/vagrant/vyos-build
     cd /home/vagrant/vyos-build
     chown -R vagrant:vagrant /home/vagrant/vyos-build
     docker build -t vyos-builder docker
     docker run --rm --privileged -v /home/vagrant/vyos-build:/vyos -w /vyos vyos-builder ./configure
     docker run --rm --privileged -v /home/vagrant/vyos-build:/vyos -w /vyos vyos-builder sudo make iso
     cp /home/vagrant/vyos-build/build/live-image-amd64.hybrid.iso /vagrant/live-image-amd64.hybrid.iso
  SHELL

end
