# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"

  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y docker.io git
     git clone https://github.com/vyos/vyos-build.git /home/vagrant/vyos-build
     cd /home/vagrant/vyos-build
     git checkout crux
     chown -R vagrant:vagrant /home/vagrant/vyos-build
     docker build -t vyos-builder docker
     docker run --rm -it --privileged -v /home/vagrant/vyos-build:/vyos -w /vyos vyos-builder ./configure
     docker run --rm -it --privileged -v /home/vagrant/vyos-build:/vyos -w /vyos vyos-builder sudo make iso
  SHELL

end
