# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"

  config.vm.provision "shell", inline: <<-SHELL
     sed -i 's/us\./es\./g' /etc/apt/sources.list
     apt-get update
     apt-get install -y docker.io git
     git clone https://github.com/vyos/vyos-build.git /home/vagrant/vyos-build
     cd /home/vagrant/vyos-build
     git checkout crux
     #git submodule update --init --recursive --remote
     #chown -R vagrant:vagrant /home/vagrant/vyos-build
     docker build -t vyos-builder docker
     #docker run --rm --privileged -v /home/vagrant/vyos-build:/vyos -w /vyos vyos-builder ./scripts/build-submodules --verbose
     #sed -i '/vyos_repo_entry/d' scripts/live-build-config
     docker run --rm --privileged -v /home/vagrant/vyos-build:/vyos -w /vyos vyos-builder ./configure --build-by="yan@grunenberger.net"  --architecture amd64 --build-type release --version 1.2.0
     docker run --rm --privileged -v /home/vagrant/vyos-build:/vyos -w /vyos vyos-builder sudo make iso
  SHELL

end
